# 版本
apiVersion: v1
kind: Pod
# 元数据
metadata:
  name: zgd-container
  labels:
    role: demo
    aaa: bbb
# 期望状态
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      env:
        - name: msg
          value: "hello world"
      command:
          - /bin/sh
          - -c
          - echo $(msg);sleep 3600;
      ports:
        - containerPort: 80
          protocol: TCP
  restartPolicy: Always
