# 多容器协同演示
# 可以用sidecar容器来帮助我们远程调用，我们不需要去注册中心获取服务具体信息，只需要调用sidecar即可
apiVersion: v1
kind: Pod
metadata:
  name: multi-pods
  labels:
    app: multi-pods
spec:
  volumes:
    - name: multi-pods-vol
      emptyDir:
        {}
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: multi-pods-vol

    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh","-c","while true;do sleep 1; date > /root/html/index.html;done;"]
      volumeMounts:
        - mountPath: /root/html
          name: multi-pods-vol
  restartPolicy: Always

