# 演示镜像pod
apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    app: static-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
