spring:
  application:
    name: demo-dubbo-nacos-ServiceA
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.59:8848
dubbo:
  scan:
    base-packages: com.zhss.demo.dubbo.nacos
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: spring-cloud://localhost